server:
  port: 8080

spring:
  application:
    name: zb-springboot-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    protocol: smtp
    host: smtp.163.com
    username: test
    password: test

mybatis-plus:
  configuration:
    use-generated-keys: true
  mapper-locations: mappers/*/*.xml
  global-config:
    db-config:
      id-type: auto

