server:
  port: 8081

spring:
  application:
    name: zb-springboot-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    protocol: smtp
    host: smtp.163.com
    username: 123456@163.com
    password: 123456
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  mapper-locations: mappers/*.xml
  global-config:
    db-config:
      id-type: auto

# actuator
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

